// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b332be4e133ae75c915c8dd2f4b1fe9ac4a45aa4/randomstring/randomstring.d.ts
declare namespace Randomstring {
    interface GenerateOptions {
        length?: number;
        readable?: boolean;
        charset?: string;
        capitalization?: string;
    }

    function generate(options?: GenerateOptions): string;
}

declare module "randomstring" {
    export = Randomstring;
}
